### ISSUE TITLE
Notebooks: alanine_dipeptide_basics question

### ISSUE THREAD

**Issue by cagrikymk** [noegroup/bgflow#11]
First of all, thank you for such a great tool!
I was trying to run "alanine_dipeptide_basics" notebook but it fails because I dont have access to "bgmol" repository. Is it an internal one? I tried searching for it but I couldnt find anything.

Thanks

**Comment by Olllom** [comment]
Hi @cagrikymk,

thanks for your interest. Indeed, the `bgmol` code was not yet public. We are still working on the final touches and on cleaning up some more meaningful examples (also in this repo); the alanine dipeptide tutorial is just meant as an educational introduction to showcase the basic components of the code. It does not represent the state of the art of Boltzmann Generators. More complex and meaningful cases will be added shortly. 

I have changed the visibility settings now but some parts of the API may change.

https://github.com/noegroup/bgmol

Cheers,
Andreas
