### ISSUE TITLE
nflows is no longer an optional dependency

### ISSUE THREAD

**Issue by LeonKlein** [noegroup/bgflow#49]
See https://github.com/noegroup/bgflow/blob/ae1dc6a9b3bcd7f0382c98614a572b2ae1b3a540/bgflow/nn/flow/transformer/spline.py#L2
This should be imported in the class.
Tests need to be changed accordingly as well.

**Comment by Olllom** [comment]
You are right, this is a bug.
It should be an optional dependency though. 

I will fix it
