### ISSUE TITLE
importing data ala dipeptide

### ISSUE THREAD

**Issue by pojeda** [noegroup/bgflow#72]
Hi, 

Thanks for making public your code! I ran successfully the notebook for ala dipeptide basics. Now, I would like to use my own protein trajectory file but I haven't found information on how data is handled/formatted for bgflow. On the lines:

```
is_data_here = os.path.isfile("Ala2TSF300.npy")
dataset = Ala2TSF300(download=(not is_data_here), read=True)
system = dataset.system
```

I noticed that "Ala2TSF300.npy" contains the data trajectory for the positions of the atoms in a row-like manner. But it is not clear to me what the method  `Ala2TSF300(download=(not is_data_here), read=True)` does, I wonder if there is any code for this?

**Comment by Olllom** [comment]
The data is directly accessed through `dataset.xyz` 
The `(not is_data_here)` just avoids multiple downloads. You can also set `download=True`, but then the data will be downloaded every time you run this cell.

**Comment by invemichele** [comment]
Hi, 

that method is imported from another library, `from bgmol.datasets import Ala2TSF300`, that can be found here https://github.com/noegroup/bgmol

**Comment by pojeda** [comment]
Hi, thanks for your comments. I wonder if the file "Ala2TSF300.npy" was obtained through the simtk.openmm toolkit?

**Comment by Olllom** [comment]
bgmol/ala2.py at main · noegroup/bgmolgithub.comIt‘s from here. See description in the file. And yes, the simulations were run using openmm. On Jan 11, 2023, at 19:30, pojeda ***@***.***> wrote:﻿
Hi, thanks for your comments. I wonder if the file "Ala2TSF300.npy" was obtained through the simtk.openmm toolkit?

**Comment by invemichele** [comment]
yes, it was obtained with OpenMM
